### ISSUE TITLE
OSX compilation troubles

### ISSUE THREAD

**Issue by kpykc** [mp3guy/Logger2#1]
Hello,

```
0/build> sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D136
```

while I was building  `Logger2` I have faced with two issues:
- to absence of header file https://github.com/mp3guy/Logger2/blob/master/src/MemoryBuffer.h#L35 :
  
  ```
  Logger2-master/src/build/../MemoryBuffer.h:35:10: fatal error: 
        'mach/x86_64/task.h' file not found
  #include <mach/x86_64/task.h>
  ```
  
  I have replaced it with `#include <mach/task.h>`
- difference for OSX/Linux socket API:
  - https://github.com/mp3guy/Logger2/blob/master/src/Communicator.cpp#L28
  
  `SOCK_NONBLOCK` not defined
  
  ```
    Logger2-master/src/Communicator.cpp:28:45: error: use
      of undeclared identifier 'SOCK_NONBLOCK'
       inSocket = socket(AF_INET, SOCK_DGRAM | SOCK_NONBLOCK, 0);
  ```
  
  I added to https://github.com/mp3guy/Logger2/blob/master/src/Communicator.h#L22 :
  
  ```
   #ifndef SOCK_NONBLOCK
   #include <fcntl.h>
   # define SOCK_NONBLOCK O_NONBLOCK
   #endif
  ```
  - https://github.com/mp3guy/Logger2/blob/master/src/Communicator.cpp#L76

`struct sockaddr_in` has no `ifa_ifu` 

```
    Logger2-master/src/Communicator.cpp:76:46: error: no
      member named 'ifa_ifu' in 'ifaddrs'
            sa = (struct sockaddr_in *) ifa->ifa_ifu.ifu_broadaddr;
```

 I have changed https://github.com/mp3guy/Logger2/blob/master/src/Communicator.cpp#L76 :

```
        #if defined __APPLE__ && defined __MACH__
        sa = (struct sockaddr_in *) ifa->ifa_broadaddr;
        #else
        sa = (struct sockaddr_in *) ifa->ifa_ifu.ifu_broadaddr;
        #endif
```

After this changes compilation succeeded and app is working. Thanks.

**Comment by mp3guy** [comment]
Hi, 

If this is all within the mac os #define blocks feel free to make a pull request and I'll merge it. 

Thanks, 
Tom

**Comment by kpykc** [comment]
Ok, I'll make a pull request.

**Comment by kpykc** [comment]
BTW, I have also changed `boost_thread` to `boost_thread-mt`

```
 target_link_libraries(Logger2                       
 >>>                      boost_thread-mt
                       OpenNI2)
```

but I'm not sure if this is my Homebrew+Boost  combination results in absence of this lib.
