### ISSUE TITLE
Kinect2 can works?

### ISSUE THREAD

**Issue by Xbbei** [mp3guy/Logger2#10]
Hi,
I use "libfreenect2" to detect and drive my kinect2. and I make the Logger2 and I run it, it will warn me that "no devices found". So it doesn't work with kinect2?

Thank you very much!

**Comment by nonlinear1** [comment]
Kinect2 can works!!! But you must change the source code. 
I succeeding in letting the Logger2 work with kinect2
here is my changing for the source code
in Logger2/src/CMakelists.txt
my os is unbuntu 16.04

after // is the source code of unchanged.
the line below // line is my changing. 
        
        //configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libOpenNI2x64.so ${CMAKE_CURRENT_BINARY_DIR}/libOpenNI2.so COPYONLY)

        configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libOpenNI2x64.so ${CMAKE_CURRENT_BINARY_DIR}/libfreenect2-openni2 COPYONLY)

        //configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libOpenNI2x86.so ${CMAKE_CURRENT_BINARY_DIR}/libOpenNI2.so COPYONLY)

        configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libOpenNI2x86.so ${CMAKE_CURRENT_BINARY_DIR}/libfreenect2-openni2 COPYONLY)
in Logger2/src/main.cpp
        
    //int width = 640;
    int width = 512;
    
    //int height = 480;
    int height = 424;
in Logger2/src/main.h
  //unsigned short depthBuffer[640 * 480 * 2];
    unsigned short depthBuffer[512 * 424 * 2];

**Comment by nonlinear1** [comment]
Kinect2 can works!!! But you must change the source code. 
I succeeding in letting the Logger2 work with kinect2
here is my changing for the source code
in Logger2/src/CMakelists.txt
my os is unbuntu 16.04

after // is the source code of unchanged.
the line below // line is my changing. 
        
        //configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libOpenNI2x64.so ${CMAKE_CURRENT_BINARY_DIR}/libOpenNI2.so COPYONLY)

        configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libOpenNI2x64.so ${CMAKE_CURRENT_BINARY_DIR}/libfreenect2-openni2 COPYONLY)

        //configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libOpenNI2x86.so ${CMAKE_CURRENT_BINARY_DIR}/libOpenNI2.so COPYONLY)

        configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libOpenNI2x86.so ${CMAKE_CURRENT_BINARY_DIR}/libfreenect2-openni2 COPYONLY)
in Logger2/src/main.cpp
        
    //int width = 640;
    int width = 512;
    
    //int height = 480;
    int height = 424;
in Logger2/src/main.h
  //unsigned short depthBuffer[640 * 480 * 2];
    unsigned short depthBuffer[512 * 424 * 2];

**Comment by nonlinear1** [comment]
copy libfreenect2-openni2 from OpenNI2 with freenect2  to Logger2/src/OpenNI2!!!

**Comment by densechen** [comment]
> copy libfreenect2-openni2 from OpenNI2 with freenect2 to Logger2/src/OpenNI2!!!
@nonlinear1 I have changed the code as you described, but still failed. And i fell confuse about the last step. 
Could you help me ?

**Comment by bcalbe** [comment]
I use
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/OpenNI2/libfreenect2-openni2x86.so ${CMAKE_CURRENT_BINARY_DIR}/libfreenect2-openni2 COPYONLY)
and it works
