### ISSUE TITLE
Primesense Carmine 1.09 issue

### ISSUE THREAD

**Issue by ndouard** [mp3guy/Logger2#7]
Hi :)

I'm trying to log data using a Primesense Carmine 1.09 sensor which is pretty much identical to an Asus Xtion Pro Live. I can perfectly do live ElasticFusion acquisitions but I find myself unable to use either logger1 or logger2. In both cases, I get a "no device found" error. 
I tried the way suggested in the README and it still fails. The device is listed as "ASUS" when running `lsusb`.

I'd greatly appreciate any help that might help me solve my problem.
Thanks!

**Comment by mp3guy** [comment]
Not really sure about using that particular version without the right driver, maybe you should try libfreenect's OpenNI2 driver.

**Comment by ndouard** [comment]
Got logger1 working by doing the following:

- Do `sudo apt-get install libopenni-dev libopenni-sensor-primesense-dev`
- Install this driver (Linux x64 in my case): http://download.dahoo.fr/Ressources/openNi/OpenNI-Compliant%20Sensor%20Driver%20v5.1.6.6/
