### ISSUE TITLE
Error in "moc_main.cxx" Generating

### ISSUE THREAD

**Issue by Xbbei** [mp3guy/Logger2#9]
Hi,
I'm make the project with Ubuntu16.04 OpenNI2(libfreenect2) Qt4 Opencv2 and so on.
cmake:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.7") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   chrono
--   system
--   date_time
--   atomic
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rosebei/下载/Logger2-master/src/build
make:
[ 14%] Generating moc_main.cxx
moc: Cannot open options file specified with @
Usage: moc [options] <header-file>
  -o<file>           write output to file rather than stdout
  -I<dir>            add dir to the include path for header files
  -E                 preprocess only; do not generate meta object code
  -D<macro>[=<def>]  define macro, with optional definition
  -U<macro>          undefine macro
  -i                 do not generate an #include statement
  -p<path>           path prefix for included file
  -f[<file>]         force #include, optional file name
  -nn                do not display notes
  -nw                do not display warnings
  @<file>            read additional options from file
  -v                 display version of moc
CMakeFiles/Logger2.dir/build.make:62: recipe for target 'moc_main.cxx' failed
make[2]: *** [moc_main.cxx] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Logger2.dir/all' failed
make[1]: *** [CMakeFiles/Logger2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
So, what's wrong with my environment?

Thank you very much!
Best wishes!
Xu Baobei

**Comment by mp3guy** [comment]
Not sure. Maybe the 下载 characters in the pathname are tripping up things?
